version: '3.8'
services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=testes-locais --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
