# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{job_name}}"
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: {{active_deadline_seconds}}
  template:
    spec:
      serviceAccountName: "{{service_account_name}}"
      initContainers:
      - name: cpu-monitor
        image: busybox
        restartPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          MAX_CPU_FILE="/etc/cpu-usage/max_cpu"
          echo 0 > $MAX_CPU_FILE
          while true; do
            if [ -f /sys/fs/cgroup/cpu.stat ]; then
              USAGE_BEF=$(grep 'usage_usec' /sys/fs/cgroup/cpu.stat | awk '{print $2}')
              sleep 1
              USAGE_AFT=$(grep 'usage_usec' /sys/fs/cgroup/cpu.stat | awk '{print $2}')
              CURRENT_CPU=$(awk "BEGIN {print ($USAGE_AFT - $USAGE_BEF) / 1000000}")
            elif [ -f /sys/fs/cgroup/cpuacct/cpuacct.usage ]; then
              USAGE_BEF=$(cat /sys/fs/cgroup/cpuacct/cpuacct.usage)
              sleep 1
              USAGE_AFT=$(cat /sys/fs/cgroup/cpuacct/cpuacct.usage)
              CURRENT_CPU=$(awk "BEGIN {print ($USAGE_AFT - $USAGE_BEF) / 1000000000}")
            else
              CURRENT_CPU=0
            fi

            MAX_CPU=$(cat $MAX_CPU_FILE)
            awk -v cur=$CURRENT_CPU -v max=$MAX_CPU 'BEGIN { if (cur > max) exit 0; exit 1 }' && echo $CURRENT_CPU > $MAX_CPU_FILE
            sleep 59
          done
        volumeMounts:
        - name: cpu-usage
          mountPath: /etc/cpu-usage
      containers:
      - name: "{{job_name}}"
        image: "{{docker_image}}"
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_UID
          value: '1337'
        - name: CLUSTERFUZZ_RELEASE
          value: "{{clusterfuzz_release}}"
        - name: UNTRUSTED_WORKER
          value: 'False'
        - name: UWORKER
          value: 'True'
        - name: USE_GCLOUD_STORAGE_RSYNC
          value: '1'
        - name: UWORKER_INPUT_DOWNLOAD_URL
          value: "{{input_url}}"
        - name: IS_K8S_ENV
          value: 'true'
        - name: DISABLE_MOUNTS
          value: 'true'
        - name: UPDATE_WEB_TESTS
          value: 'False'
        securityContext:
          privileged: true
          capabilities:
            add:
            - ALL
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /etc/cpu-usage
          name: cpu-usage
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1.9Gi
      - name: cpu-usage
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0